name: "say hello on each push"
on:
  push: #executed on all push

jobs:
  say_hello: #first job declaration
    name: "Say hello"
    runs-on: ubuntu-latest
    steps: 
      # the following step execute a shel script
      - name: "Say hello"
        run: |
          echo "HEllo, world !"
